const cartas = new Map()
cartas.set(1, 'Descrição do Curso')
cartas.set(2, 'Pré-Requisitos')
cartas.set(3, 'Objetivos Educacionais')
cartas.set(4, 'Objetivos Gerais do Curso')
cartas.set(5, 'Objetivos Metodológicos')
cartas.set(6, 'Sucesso do Professor')
cartas.set(7, 'Sucesso do Aluno')
cartas.set(8, 'Sucesso do Método PBL')
cartas.set(9, 'Sucesso do Curso')
cartas.set(10, 'Captação & Seleção')
cartas.set(11, 'Descrição Textual')
cartas.set(12, 'Apresentação')
cartas.set(13, 'Validação')
cartas.set(14, 'Modificação')
cartas.set(15, 'Infraestrutura de TIC')
cartas.set(16, 'Infraestrutura Física')
cartas.set(17, 'Ambiente Virtual')
cartas.set(18, 'Cliente')
cartas.set(19, 'Aluno')
cartas.set(20, 'Professor')
cartas.set(21, 'Tutor Técnico')
cartas.set(22, 'Tutor PBL')
cartas.set(23, 'Coordenador')
cartas.set(24, 'Módulo Educacional')
cartas.set(25, 'Fontes de Referências')
cartas.set(26, 'Avaliação de Conteúdo')
cartas.set(27, 'Processo de Resolução de Problema')
cartas.set(28, 'Avaliação de Resultado')
cartas.set(29, 'Avaliação de Desempenho')
cartas.set(30, 'Avaliação de Satisfação do Cliente')
cartas.set(31, 'Avaliação Docente')
cartas.set(32, 'Avaliação dos Objetivos Metodológicos')
cartas.set(33, 'Avaliação do Curso')
cartas.set(34, 'Formação de Equipe')
cartas.set(35, 'Processo de Aprendizagem')
cartas.set(36, 'Agenda de Aulas')
cartas.set(37, 'Agenda de Avaliações')
cartas.set(38, 'Agenda de Entregas')
cartas.set(39, 'Riscos Metodológicos')
cartas.set(40, 'Riscos Acadêmicos e Administrativos')

export default cartas
